// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA3i-V5U75Awygv5Cg13uqC33lTkL2JsMI',
    appId: '1:443923022995:web:3d0ae7b5dd344fa8ccf966',
    messagingSenderId: '443923022995',
    projectId: 'android-kutuphane-otomasyonu',
    authDomain: 'android-kutuphane-otomasyonu.firebaseapp.com',
    storageBucket: 'android-kutuphane-otomasyonu.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDFYrPgkFaGDeAiG9U_b8mRymYOtGp6s_c',
    appId: '1:443923022995:android:39787c8d913724f1ccf966',
    messagingSenderId: '443923022995',
    projectId: 'android-kutuphane-otomasyonu',
    storageBucket: 'android-kutuphane-otomasyonu.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyApKmWre0JjyjTrlOMlucerZBN1LQQ1KyA',
    appId: '1:443923022995:ios:1afbe91b9a56e4e7ccf966',
    messagingSenderId: '443923022995',
    projectId: 'android-kutuphane-otomasyonu',
    storageBucket: 'android-kutuphane-otomasyonu.appspot.com',
    iosBundleId: 'com.example.kutuphaneOtomasyonu',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyApKmWre0JjyjTrlOMlucerZBN1LQQ1KyA',
    appId: '1:443923022995:ios:72f6d52811873622ccf966',
    messagingSenderId: '443923022995',
    projectId: 'android-kutuphane-otomasyonu',
    storageBucket: 'android-kutuphane-otomasyonu.appspot.com',
    iosBundleId: 'com.example.kutuphaneOtomasyonu.RunnerTests',
  );
}
